__version__ = "0.1.0"
__title__ = "JMS Porthole"
__description__ = "Janus Monitoring Suite — remote monitoring, broadcasting, and recon toolkit"
__acronym__ = "JMS"
__acronym_full__ = "Janus Monitoring Suite"
